// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeKHKqu2n0-sYIKOOh7iIx7Z5SKMU6O8E',
    appId: '1:275250336556:web:7482b2746b3ccbcb915289',
    messagingSenderId: '275250336556',
    projectId: 'stusfirebaseproject',
    authDomain: 'stusfirebaseproject.firebaseapp.com',
    databaseURL: 'https://stusfirebaseproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stusfirebaseproject.appspot.com',
    measurementId: 'G-JY6J2MZRZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsk9a5_8rE7smwZxECNVXMIIoA3R9FJ44',
    appId: '1:275250336556:android:2a51cb84d9109fdf915289',
    messagingSenderId: '275250336556',
    projectId: 'stusfirebaseproject',
    databaseURL: 'https://stusfirebaseproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stusfirebaseproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC4bmJZen-J0NhsjUsCeyOQFST0RlVPeA',
    appId: '1:275250336556:ios:f1270aabe0796e72915289',
    messagingSenderId: '275250336556',
    projectId: 'stusfirebaseproject',
    databaseURL: 'https://stusfirebaseproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stusfirebaseproject.appspot.com',
    iosClientId: '275250336556-pjg5c751l5plud759ih2ddgr7351u613.apps.googleusercontent.com',
    iosBundleId: 'com.stusapps.findMyTribe',
  );
}
